Repository datenanfragen/data, pull requests merged in 2020-11, with the labels that each got.

#815 Add ' Renault Bank direkt' (community contribution)
  companies/renault-bank-direkt.json
Labels: record, via-suggest-api

#813 Add 'unitedbase Vertriebsgesellschaft mbH' (community contribution)
  companies/unitedbase.json
Labels: record, via-suggest-api

#817 Add 'Figuya GmbH' (community contribution)
  companies/figuya.json
Labels: record, via-suggest-api

#787 Add 'EDEKA Minden-Hannover Stiftung & Co. KG' (community contribution)
  companies/goerge-markt.json
Labels: record, via-suggest-api

#794 Add 'Edeka Zentrale AG & Co. KG' (community contribution)
  companies/edeka-zentrale.json
Labels: record, via-suggest-api

#795 Add 'Starbucks' (community contribution)
  companies/starbucks-de.json
Labels: record, via-suggest-api

#798 Update 'Bertelsmann SE & Co. KGaA' (community contribution)
  companies/arvato-bertelsmann.json
Labels: record, via-suggest-api

#801 Add 'kleiderkreisel.de' (community contribution)
  companies/kleiderkreisel-de.json
  companies/vinted-uab-cz.json
  companies/vinted-uab-lt.json
  companies/vinted-uab-pl.json
  companies/vinted-uab-uk.json
  companies/vinted-uab.json
Labels: record, via-suggest-api

#814 Add 'Advertising.R' (community contribution)
  companies/ewealth-cc.json
Labels: record, via-suggest-api

#816 Fix email field in fielmann-de.json
  companies/fielmann-de.json
Labels: bug, record

#796 Add 'Netto Marken-Discount AG & Co. KG' (community contribution)
  companies/nes-gmbh.json
  companies/netto-discount.json
  companies/o2-de.json
Labels: record, via-suggest-api

#821 Add 'Chase Debt Ltd' (community contribution)
  companies/chasedebt-co.json
Labels: record, via-suggest-api

#822 Add Bird, Tier, and Voi
  bird-rides-europe.json
  tier-mobility.json
  voi-technology-ab.json
Labels: record

#824 Add 'NatWest Group plc ' (community contribution)
  companies/natwest.json
Labels: record, via-suggest-api

#830 Add 'Südtiroler Sparkasse AG Niederlassung München' (community contribution)
  companies/suedspa-de.json
Labels: record, via-suggest-api

#827 Add 'Opel Bank S.A. Niederlassung Deutschland' (community contribution)
  companies/opelbank-de.json
Labels: record, via-suggest-api

#828 Add 'Coöperatieve Rabobank U.A., Zweigniederlassung Frankfurt am Main' (community contribution)
  companies/rabodirect-de.json
Labels: record, via-suggest-api

#834 Add 'PFALZWERKE AKTIENGESELLSCHAFT' (community contribution)
  companies/pfalzwerke.json
Labels: record, via-suggest-api

#839 Add 'Arkose Labs, Inc.' (community contribution)
  companies/arkoselabs.json
Labels: record, via-suggest-api

#812 Update 'ABIS GmbH' (community contribution)
  companies/abis.json
Labels: record, via-suggest-api

#837 Add 'academia.edu' (community contribution)
  companies/academia-edu.json
Labels: record, via-suggest-api

#835 Add 'CONCORDIA Sozialprojekte Stiftung Deutschland' (community contribution)
  companies/concordia-sozialprojekte.json
Labels: record, via-suggest-api

#843 Unify addresses in Spain, fixes #842
  companies/funidelai.json
  companies/verse.json
  supervisory-authorities/esaepa.json
Labels: record

#841 Add 'Change.org, Servicios Promocionales España, S.L.' (community contribution)
  companies/change-org.json
Labels: record, via-suggest-api

#838 Add 'Starlink Germany GmbH ' (community contribution)
  companies/starlink-germany-gmbh.json
Labels: record, via-suggest-api

#836 Add 'palantir' (community contribution)
  companies/palantir.json
Labels: record, via-suggest-api

#833 Add 'BioNTech SE' (community contribution)
  companies/biontech.json
Labels: record, via-suggest-api

#856 Add 'Sparda-Bank Hessen eG' (community contribution)
  companies/sparda-hessen.json
Labels: record, via-suggest-api

#849 Update 'Sony Interactive Entertainment Europe Limited' (community contribution)
  companies/playstation-com.json
Labels: record, via-suggest-api

#844 Update 'Imgur Inc.' (community contribution)
  companies/imgur.json
Labels: record, via-suggest-api

#851 Update 'Media Information Systems Deutschland GmbH' (community contribution)
  companies/mediainformationsystems.json
Labels: record, via-suggest-api

#852 Add 'Aufstehen Trägerverein e.V.' (community contribution)
  companies/aufstehen.json
Labels: record, via-suggest-api

#853 Add 'BWI GmbH' (community contribution)
  companies/bwi.json
Labels: record, via-suggest-api

#831 Add 'Südtiroler Sparkasse AG' (community contribution)
  companies/suedtiroler-sparkasse.json
Labels: record, via-suggest-api

#859 Update 'JetBrains s.r.o.' (community contribution)
  companies/jetbrains-com.json
Labels: record, via-suggest-api

#862 Add 'IKK Classic ' (community contribution)
  companies/ikk-classic.json
Labels: record, via-suggest-api
