Repository datenanfragen/data, pull requests merged in 2020-10, with the labels that each got.

#722 Closes #23: Add remaining edaa.eu companies
  companies/burda-forward.json
  companies/exponential-com.json
  companies/fonecta-fi.json
  companies/goldbach-at.json
  companies/goldbach-ch.json
  companies/goldbach-de.json
  companies/neodatagroup.json
  companies/next14.json
  companies/nextroll.json
  companies/plista.json
  companies/q-division.json
  companies/sevenonemedia.json
Labels: record

#725 Added more Italian companies
  companies/octo-telematics.json
  companies/reply.json
  companies/sia.json
  texa.json
Labels: record

#731 Add 'Renault Deutschland AG' (community contribution)
  companies/renault-de.json
Labels: record, via-suggest-api

#732 Add 'NISSAN Center Europe GmbH' (community contribution)
  companies/nissan-de.json
Labels: record, via-suggest-api

#733 Add 'Volksbank Böblingen eG' (community contribution)
  companies/vereinigte-volksbank.json
Labels: record, via-suggest-api

#734 Add 'Volksbank Plochingen eG' (community contribution)
  companies/volksbank-plochingen.json
Labels: record, via-suggest-api

#736 Add 'Sparda-Bank West eG' (community contribution)
  companies/sparda-west.json
Labels: record, via-suggest-api

#737 Add 'NIBC Bank N.V.' (community contribution)
  companies/nibcdirect.json
Labels: record, via-suggest-api

#735 Added lego, playmobil.de and updated ebay-de
  companies/ebay-de.json
  companies/lego.json
  companies/playmobil-de.json
Labels: record

#738 Add 'Holvi Payment Services Oy'
  companies/holvi.json
Labels: record

#741 Add "Volkswagen"
  companies/volkswagen-ag.json
Labels: record

#747 added Daedalic, Koch media, and Crows Crows Crows; added Blue Byte to Ubisoft
  companies/crows-crows-crows.json
  companies/daedalic-entertainment.json
  companies/koch-media-gmbh.json
  companies/ubisoft.json
Labels: record

#750 Updated some records
  companies/1plus-agency.json
  companies/3dhubs.json
  companies/4wave.json
  companies/abebooks.json
Labels: record

#753 Update 'adroll' (community contribution)
  companies/adroll.json
Labels: record, via-suggest-api

#754 Add Servizio Elettrico Nazionale S.p.A.
  companies/servizio-elettrico-nazionale.json
Labels: record

#755 Add Italiaonline S.p.A.
  companies/italiaonline.json
Labels: record

#756 Add Liechtensteinische Landesbank AG
  companies/liechtensteinische-landesbank-ag.json
Labels: record

#758 Add 'Viessmann Werke GmbH & Co. KG' (community contribution)
  companies/viessmann.json
Labels: record, via-suggest-api

#759 Add LGT Gruppe Holding AG
  companies/lgt-bank.json
Labels: record

#760 Add 'Media Information Systems Deutschland GmbH' (community contribution)
  companies/mediainformationsystems.json
Labels: record, via-suggest-api

#740 Add BITel, T.W.O. and Stadtwerke Bielefeld
  companies/bitel.json
  companies/stadtwerke-bielefeld.json
  companies/technische-werke-osning.json
Labels: record

#765 Add 'marketwing GmbH' (community contribution)
  companies/marketwing.json
Labels: record, via-suggest-api

#769 Add "Shoop Germany GmbH"
  companies/shoop.json
Labels: record

#772 Add Dutch translation for complaint
  templates/nl/complaint.txt
Labels: template

#774 Dutch translation for admonition
  templates/nl/admonition.txt
Labels: template

#767 Add 'JustWatch GmbH' (community contribution)
  companies/justwatch.json
Labels: record, via-suggest-api

#768 Add 'G2A.COM Limited' (community contribution)
  companies/g2a.json
Labels: record, via-suggest-api

#770 Add 'StarzPlay Direct UK Limited' (community contribution)
  companies/starz.json
Labels: record, via-suggest-api

#771 Update 'likee' (community contribution)
  companies/likee.json
Labels: record, via-suggest-api

#775 Update 'schober' (community contribution)
  companies/schober.json
Labels: record, via-suggest-api

#776 Add 'WoltLab GmbH' (community contribution)
  companies/woltlab.json
Labels: record, via-suggest-api

#783 Make templates clearer (IT)
  templates/it/access-default.txt
  templates/it/access-tracking.txt
  templates/it/admonition.txt
  templates/it/erasure-default.txt
  templates/it/objection-default.txt
  templates/it/rectification-default.txt
Labels: template

#784 Update 'BNP Paribas S.A. Niederlassung Deutschland' (community contribution)
  companies/consorsfinanz.json
Labels: record, via-suggest-api

#778 Add 'bunq B.V. ' (community contribution)
  companies/bunq.json
Labels: record, via-suggest-api

#779 Add 'Untappd, Inc.' (community contribution)
  companies/untappd.json
Labels: record, via-suggest-api

#780 Add 'Union Investment Gruppe' (community contribution)
  companies/union-investment.json
Labels: record, via-suggest-api

#782 Closes #781: Add N-Ergie
  companies/n-ergie.json
Labels: record

#788 Explicitly state that the protocol is needed in the schema
  schema.json
Labels: bug, schema

#789 Added corona-anmeldung and BarCov
  companies/barcov-de.json
  companies/corona-anmeldung.json
Labels: record

#793 Add 'BÄR GmbH' (community contribution)
  companies/baer-schuhe.json
Labels: record, via-suggest-api

#792 Add 'we.CONECT Global Leaders GmbH' (community contribution)
  companies/we-conect.json
Labels: record, via-suggest-api

#804 Translate erasure to Dutch
  templates/nl/erasure-default.txt
Labels: template

#805 Add 'itzehoer' (community contribution)
  companies/itzehoer.json
Labels: record, via-suggest-api

#806 Add 'Blendle B.V.'
  companies/blendle.json
Labels: record

#803 Update triller.json
  companies/triller.json
Labels: record

#810 Add 'Scalable Capital' and 'Baader Bank'
  companies/baaderbank.json
  companies/scalablecapital.json
Labels: record

#791 Add 'nhi² AG Interviews International' (community contribution)
  companies/nhi2.json
Labels: record, via-suggest-api

#807 Add 'East Bank Club The Fitness Factory GmbH'
  companies/eastbankclub.json
Labels: record

#797 Add 'M-net Telekommunikations GmbH' (community contribution)
  companies/m-net.json
Labels: record, via-suggest-api
