Repository datenanfragen/data, pull requests merged in 2021-07, with the labels that each got.

#1165 Add 'Swapfiets' (community contribution)
  companies/swapfiets-de.json
Labels: record, via-suggest-api

#1167 Clarify that we are requesting a copy in access templates (DE + EN)
  templates/de/access-bundesjustizamt.txt
  templates/de/access-bundespolizei.txt
  templates/de/access-default.txt
  templates/de/access-drk-brandenburg-datenleck.txt
  templates/de/access-evangelische-kirche.txt
  templates/de/access-katholische-kirche.txt
  templates/de/access-lka-nds.txt
  templates/de/access-tracking.txt
  templates/en/access-default.txt
  templates/en/access-tracking.txt
Labels: template

#1176 Update 'paydirekt GmbH' (community contribution)
  companies/paydirekt.json
Labels: record, via-suggest-api

#1166 Add 'Condé Nast Holdings Limited' (community contribution)
  companies/condenast.json
Labels: record, via-suggest-api

#1169 Add 'runtastic' (community contribution)
  companies/runtastic.json
Labels: record, via-suggest-api

#1175 Add 'Shenzhen Qingniu Software Co., Ltd.' (community contribution)
  companies/qnniu.json
Labels: record, via-suggest-api

#1170 Add 'voxpark GmbH' (community contribution)
  companies/voxpark.json
Labels: record, via-suggest-api

#1177 Add 'RSG Group' (community contribution)
  companies/rsggroup.json
Labels: record, via-suggest-api

#1161 Add 'Phoenix Contact' (community contribution)
  companies/phoenixcontact.json
Labels: record, via-suggest-api

#1183 Update 'culture4life GmbH' (community contribution)
  companies/luca-app.json
Labels: record, via-suggest-api

#1184 Add 'Spreadshirt' (community contribution)
  companies/spreadshirt.json
Labels: record, via-suggest-api

#1186 Set 'suggest-transport-medium' to 'email' for privacy-related emails
  companies/a1-austria.json
  companies/abis.json
  companies/adjust-com.json
  companies/alphonso-tv.json
  companies/arag-de.json
  companies/astrid-lindgren-schule-bs.json
  companies/autobahn.json
  companies/bonifyde.json
  companies/creditreform-verband.json
  companies/dainst-bund.json
  companies/destatis.json
  companies/dm-drogerie.json
  companies/dpma-bund.json
  companies/dsg-retail.json
  companies/e-fellows.json
  companies/ert-gr.json
  companies/gaussschule-bs.json
  companies/gsaltmhl-bs.json
  companies/gsasberg-bs.json
  companies/gsbue-bs.json
  companies/heinekingmedia.json
  companies/hvf-bs.json
  companies/igsquerum-bs.json
  companies/imgur.json
  companies/iserv.json
  companies/julius-kuehn-bund.json
  companies/ludwigvonkapff.json
  companies/meetup-com.json
  companies/mri-bund.json
  companies/neue-oberschule-bs.json
  companies/otto-bennemann-schule-bs.json
  companies/raabeschule-bs.json
  companies/rhs-bs.json
  companies/rockerbox.json
  companies/ruyterast.json
  companies/schober-direct-media.json
  companies/semasio.json
  companies/sgd.json
  companies/shoop.json
  companies/shutterstock.json
  companies/stadtausstellung.json
  companies/teads.json
  companies/teambank-de.json
  companies/teamviewer.json
  companies/technikakademie-bs.json
  companies/threema.json
  companies/thuenen-bund.json
  companies/trusted-traffic.json
  companies/vodafone-de.json
  companies/webtrekk.json
  companies/wilhelm-gym-bs.json
  companies/wolterskluwer-global.json
  companies/wolterskluwer.json
  companies/xaxis-com.json
  companies/yesasia.json
  companies/zomato.json
  companies/zucchetti.json
Labels: record

#1151 Add 'Torquato AG' (community contribution)
  companies/torquato.json
Labels: record, via-suggest-api

#1156 Add 'Outwood Academy Redcar' (community contribution)
  companies/outwood-redcar.json
Labels: record, via-suggest-api

#1171 Add 'Vonza HQ' (community contribution)
  companies/vonza.json
Labels: record, via-suggest-api

#1181 Add 'FABER Lotto GmbH & Co. KG' (community contribution)
  companies/faber-lotto.json
Labels: record, via-suggest-api

#1187 Fix bonprix' address
  companies/bonprix.json
Labels: record

#1193 Add 'Fakespot Inc' (community contribution)
  companies/fakespot.json
Labels: record, via-suggest-api

#1194 Add 'cyon GmbH' (community contribution)
  companies/cyon.json
Labels: record, via-suggest-api

#1189 Add 'Fantastic Academy' (community contribution)
  companies/1st-online-solutions-limited.json
Labels: record, via-suggest-api

#1190 Add 'Proshop a/s' (community contribution)
  companies/proshop-de.json
Labels: record, via-suggest-api

#1195 more precise fax and phone regex
  schema.json
Labels: bug, schema

#1197 Add 'Fitbit' (community contribution)
  companies/fitbit.json
Labels: record, via-suggest-api
