Repository datenanfragen/data, pull requests merged in 2021-05, with the labels that each got.

#1102 Add 'goldgas GmbH' (community contribution)
  companies/goldgas.json
Labels: record, via-suggest-api

#1058 Add 'Domoguide' (community contribution)
  companies/domoguide.json
Labels: record, via-suggest-api

#1100 Add 'VR Bank Rhein-Neckar eG' (community contribution)
  companies/vrbank.json
Labels: record, via-suggest-api

#1101 Add 'DREWAG - Stadtwerke Dresden GmbH' (community contribution)
  companies/energiemanufaktur.json
Labels: record, via-suggest-api

#1103 Add 'Deutscher Zentralverein homöopathischer Ärzte e.V.' (community contribution)
  companies/dzvhae.json
Labels: record, via-suggest-api

#1105 Add 'KKH Kaufmännische Krankenkasse ' (community contribution)
  companies/kkh-krankenkasse.json
Labels: record, via-suggest-api

#1106 Add 'sofort-impfen.de' (community contribution)
  companies/sofort-impfen-de.json
Labels: record, via-suggest-api

#1089 Add 'Stadt Hamburg - Bezirksamt Hamburg Mitte' (community contribution)
  companies/hamburg-bezirksamt-mitte.json
Labels: record, via-suggest-api

#1107 Closes #825: Untangle Match Group services
  companies/ablo-live.json
  companies/affinity-gb.json
  companies/affiny-fr.json
  companies/blk-app.json
  companies/chispa-app.json
  companies/disonsdemain.json
  companies/lexa-nl.json
  companies/lexamore-nl.json
  companies/lovescout24.json
  companies/match-dk.json
  companies/match-fi.json
  companies/match-gb.json
  companies/match-group.json
  companies/match-no.json
  companies/match-se.json
  companies/matchaffinity-dk.json
  companies/matchaffinity-fi.json
  companies/matchaffinity-ie.json
  companies/matchaffinity-no.json
  companies/matchaffinity-se.json
  companies/meetic-es.json
  companies/meetic-fr.json
  companies/meetic-it.json
  companies/meetic-nl.json
  companies/meetic-pt.json
  companies/meeticaffinity-be.json
  companies/meeticaffinity-es.json
  companies/meeticaffinity-it.json
  companies/meeticaffinity-pt.json
  companies/mtch-technology.json
  companies/neu-de.json
  companies/ourtime-es.json
  companies/ourtime-gb.json
  companies/ourtime-it.json
  companies/ourtime-nl.json
  companies/ourtime-se.json
  companies/pairs-lv.json
  companies/partner-de.json
  companies/twoo.json
  companies/zweisam.json
  test-records.js
Labels: record

#1109 Update 'Outbrain, Inc.' (community contribution)
  companies/outbrain.json
Labels: record, via-suggest-api

#1113 Update 'Alibaba.com Singapore E-Commerce Private Limited' (community contribution)
  companies/alibaba.json
Labels: record, via-suggest-api

#1110 Add 'PXN GmbH' (community contribution)
  companies/pxn-digital.json
Labels: record, via-suggest-api

#1108 Update 'ING (ING-DiBa AG)' (community contribution)
  companies/ing-diba.json
Labels: record, via-suggest-api

#1114 Add 'Ideawise Limited' (community contribution)
  companies/fetisch-de.json
  companies/gay-de.json
  companies/kaufmich-com.json
  companies/poppen-de.json
Labels: record, via-suggest-api

#1115 Add 'BOLD Company' (community contribution)
  companies/bold-company.json
Labels: record, via-suggest-api

#1117 Add 'ContentScope GmbH' (community contribution)
  companies/sooner.json
Labels: record, via-suggest-api

#1118 Update 'Takeaway.com Group B.V.' (community contribution)
  companies/takeaway-com.json
Labels: record, via-suggest-api

#1125 Schema: Remove overseas territories that aren't actually countries
  schema.json
Labels: schema
