Repository datenanfragen/data, pull requests merged in 2022-01, with the labels that each got.

#1601 Add 'Weltbett GmbH' (community contribution)
  companies/weltbett-de.json
Labels: record, via-suggest-api

#1593 Add 'Bumble' (community contribution)
  companies/bumble.json
Labels: record, via-suggest-api

#1594 Add 'Jobomi UG (haftungsbeschränkt)' (community contribution)
  companies/jobomi.json
Labels: record, via-suggest-api

#1596 Add 'AS Mintos Marketplace' (community contribution)
  companies/mintos.json
Labels: record, via-suggest-api

#1599 Add 'EOD European Online Distribution GmbH' (community contribution)
  companies/vivobarefoot.json
Labels: record, via-suggest-api

#1600 Add 'CleverReach GmbH & Co. KG' (community contribution)
  companies/cleverreach.json
Labels: record, via-suggest-api

#1602 Update 'Wikimedia Foundation, Inc.' (community contribution)
  companies/wikimedia-foundation.json
Labels: record, via-suggest-api

#1598 Add 'Hillside (Sports) ENC' (community contribution)
  companies/bet365.json
Labels: record, via-suggest-api

#1606 Add 'Shapr3D Zrt.' (community contribution)
  companies/shapr3d.json
Labels: record, via-suggest-api

#1597 Add 'PinBet Malta Ltd' (community contribution)
  companies/pinnacle.json
Labels: record, via-suggest-api

#1607 Add 'Invoice2go, Inc.' (community contribution)
  companies/invoice-2go.json
Labels: record, via-suggest-api

#1603 Add 'Nero AG' (community contribution)
  companies/nero.json
Labels: record, via-suggest-api

#1611 Add 'goflink.com' (community contribution)
  companies/goflink-com.json
Labels: record, via-suggest-api

#1620 New PGP-key for Berlin BfDI
  supervisory-authorities/deberlbdi.json
Labels: bug, record

#1622 Update 'Media Information Systems Deutschland GmbH' (community contribution)
  companies/mediainformationsystems.json
Labels: record, via-suggest-api

#1619 Add 'BIOMARIS GmbH & Co. KG' (community contribution)
  companies/biomaris.json
Labels: record, via-suggest-api

#1618 Add 'SAZ Services AG' (community contribution)
  companies/saz.json
Labels: record, via-suggest-api

#1624 Add 'Gartner' (community contribution)
  companies/gartner.json
Labels: record, via-suggest-api

#1625 Update 'Newfold Digital, Inc.' (community contribution)
  companies/dreamscape-networks.json
  companies/web-com.json
Labels: record, via-suggest-api

#1626 Update 'Neatnik LLC' (community contribution)
  companies/neatnik.json
Labels: record, via-suggest-api

#1623 Add 'Adressen-kaufen.cc' (community contribution)
  companies/adressen-kaufen.json
  companies/neatnik.json
Labels: record, via-suggest-api

#1614 Add "Johannes Gerstäcker Verlag GmbH"
  companies/gerstaecker-verlag.json
Labels: record

#1612 Add 'poolworks (Germany) Ltd.' (community contribution)
  companies/meinvz.json
Labels: record, via-suggest-api

#1610 Add 'Direct Scouts GmbH' (community contribution)
  companies/directscouts.json
Labels: record, via-suggest-api

#1505 Update 'Alpha Exploration Co.' (community contribution)
  companies/joinclubhouse.json
Labels: record, via-suggest-api

#1631 Add 'Wattpad Corp.' (community contribution)
  companies/wattpad.json
Labels: record, via-suggest-api

#1630 Add 'Envivas Krankenversicherung AG' (community contribution)
  companies/envivas.json
Labels: record, via-suggest-api

#1640 Add 'McGraw Hill LLC' (community contribution)
  companies/mheducation.json
Labels: record, via-suggest-api

#1639 Add 'Dr. Susanne Morath & Dr. Hendrik Schöll - Plastische und Ästhetische Chirurgie' (community contribution)
  companies/plastische-chirurgie-muenchen-ms.json
Labels: record, via-suggest-api

#1644 Add 'TYPEFORM, S.L.' (community contribution)
  companies/cabify.json
  companies/typeform.json
Labels: record, via-suggest-api

#1642 Update 'Clicksco Digital Limited' (community contribution)
  companies/clicksco.json
Labels: record, via-suggest-api
