Repository datenanfragen/data, pull requests merged in 2023-06, with the labels that each got.

#2194 Add Spanish Axel Springer properties
  companies/axel-springer-es.json
Labels: record

#2205 Add 'Unstoppable Domains Inc.' (community contribution)
  companies/unstoppabledomains.json
Labels: record, via-suggest-api

#2076 Update 'EIS GmbH' (community contribution)
  companies/eis-erotik.json
Labels: record, via-suggest-api

#2185 Update schema.json
  schema.json
Labels: schema

#2049 Update 'Trade Republic Bank GmbH' (community contribution)
  companies/trade-republic-bank-gmbh.json
Labels: record, via-suggest-api

#2200 Update 'Vermieterwelt GmbH' (community contribution)
  companies/vsk-de.json
Labels: record, via-suggest-api

#2192 Update 'Solaris SE' (community contribution)
  companies/solarisbank.json
Labels: record, via-suggest-api

#2201 Update 'infoscore Consumer Data GmbH' (community contribution)
  companies/infoscore.json
Labels: record, via-suggest-api

#2058 Update 'CTS EVENTIM AG & Co. KGaA' (community contribution)
  companies/eventim.json
Labels: record, via-suggest-api

#2035 Update 'EWE AG' (community contribution)
  companies/ewe-de.json
Labels: record, via-suggest-api

#2063 Update 'momox SE' (community contribution)
  companies/momox.json
Labels: record, via-suggest-api

#2046 Update 'Telekom Deutschland GmbH' (community contribution)
  companies/telekom-de.json
Labels: record, via-suggest-api

#2202 Update 'C&A Mode GmbH & Co. KG' (community contribution)
  companies/c-and-a.json
Labels: record, via-suggest-api

#2047 Update 'Aspiro AB' (community contribution)
  companies/tidal.json
Labels: record, via-suggest-api

#2187 Update 'Microsoft Ireland Operations Ltd.' (community contribution)
  companies/microsoft.json
Labels: record, via-suggest-api

#2159 Add 'hygi.de GmbH & Co. KG' (community contribution)
  companies/hygi-de.json
Labels: record, via-suggest-api

#2230 Update 'Virtual Minds GmbH' (community contribution)
  companies/theadex.json
Labels: record, via-suggest-api
